### ISSUE TITLE
Please support working without xdg-utils on Linux

### ISSUE THREAD

**Issue by joshtriplett** [amodm/webbrowser-rs#2]
On Linux, opening the default browser uses xdg-open, part of xdg-utils; however, nothing in a default desktop install requires the installation of xdg-utils.  Please consider supporting some fallbacks, such as gvfs-open, or parsing the `$BROWSER` environment variable directly.

**Comment by amodm** [comment]
Thanks for the input @joshtriplett. I'd originally sourced the choice of command on Linux from [this stackoverflow discussion](https://unix.stackexchange.com/questions/295359/what-program-to-use-to-open-files-gnome-open-gvfs-open-xdg-open-etc/295361).

Will address this as:
1. Use browser variable if available 
2. Use xdg-open as a fallback

I think using the browser variable should be sufficient instead of adding something like gvfs-open

**Comment by joshtriplett** [comment]
@amodm Thanks for the update.  I mostly mentioned gvfs-open because unlike xdg-open, it's installed by default in GNOME environments, and it still respects users' app selections in the GNOME preferences (which don't set `$BROWSER`).

**Comment by amodm** [comment]
@joshtriplett incorporated in v0.2.2 on crates.io
