### ISSUE TITLE
Is that okay to just implement by using the Windows Command Prompt ?

### ISSUE THREAD

**Issue by BlackSunDangerise** [amodm/webbrowser-rs#77]
It will be very easy to just send commands to launch the webrowser , also more options can be implemented

**Comment by amodm** [comment]
It isn't clear to me what you mean here.

While the windows command prompt can be used to open URLs, that approach fails if the user (say a web developer) has an IDE associated for opening `.html` files.

Ensuring opening of a web browser is the first of the [Consistent Behaviour](https://github.com/amodm/webbrowser-rs/tree/main#consistent-behaviour) guarantees made by this crate. Otherwise, there would be no need for this crate to exist independently of the [open](https://crates.io/crates/open) crate.
