### ISSUE TITLE
Consider respecting the $BROWSER environment variable on Windows

### ISSUE THREAD

**Issue by jrmuizel** [amodm/webbrowser-rs#78]
VS Code [uses this environment variable](https://github.com/microsoft/vscode/blob/01f46bb5357baa8f3b9da690e1e34eb78e09a72b/src/vs/server/node/extensionHostConnection.ts#L63) to allow opening a browser over ssh.

webbrowser-rs respects $BROWSER on Linux and works well over a remote connection there. However, on Windows it does not.

**Comment by amodm** [comment]
It's not supported on Windows because the origin of this is in [Unix systems](https://manpages.debian.org/bookworm/man-db/man.1.en.html#BROWSER). The problem with blindly extending the same on Windows is that if at all there are any Windows environments which use this envvar in a way differently than on Unix, it can cause bad surprises, or even a security risk. On Unix that isn't an issue because it's a _well known_ envvar.

Can you please help me understand the scenario here? In what way does this crate come into the picture in this VSCode workflow? Also, if at all it's needed to support `$BROWSER` in Windows, does gating it under a `feature` suffice (for reasons mentioned above)?

**Comment by jrmuizel** [comment]
[samply](https://github.com/mstange/samply) uses this crate to open profiles in a webbrowser. When running samply via ssh in a VS Code terminal to unix remote system, VS Code overwrites $BROWSER so that webbrowser-rs will use the local browser instead of trying to use a remote one. 

When using ssh in a VS code terminal to a Windows remote system this won't work, because webbrowser-rs doesn't use the $BROWSER that's set by VS Code. Perhaps it makes sense to only use $BROWSER on Windows when being run via ssh (I think this is called a non-interactive session).

**Comment by amodm** [comment]
Closing this issue for now. Please feel free to reopen if you encounter scenarios where this is needed.
