### ISSUE TITLE
Python VS Rust webbrowser inconsistency

### ISSUE THREAD

**Issue by i1Fury** [amodm/webbrowser-rs#80]
When using Python's `webbrowser.open()` for a `discord:///channels/.../...` uri scheme, everything functions as you would expect. It immediately opens discord.

When using your Rust library, it opens an empty chrome window.

System: Windows 10
Default Browser: Chrome Version 122.0.6261.129 (Official Build) (64-bit)
webbrowser = "0.8.13"

**Comment by amodm** [comment]
`webbrowser` crate specifically focusses on opening up a web browser, irrespective of the scheme used. It's part of its design for security & [Consistent Behaviour](https://github.com/amodm/webbrowser-rs#consistent-behaviour) guarantees. If you're looking to open the default program based on the scheme, instead of the web browser, better to use something like [open](https://crates.io/crates/open).

**Comment by i1Fury** [comment]
> `webbrowser` crate specifically focusses on opening up a web browser, irrespective of the scheme used. It's part of its design for security & [Consistent Behaviour](https://github.com/amodm/webbrowser-rs#consistent-behaviour) guarantees. If you're looking to open the default program based on the scheme, instead of the web browser, better to use something like [open](https://crates.io/crates/open).

Thank you! I was actually looking for that one originally when working on this project because i remembered using that functionality in the past, but ended up getting it mixed with yours. 🙏
